### ISSUE TITLE
 How can I download this plugin via NPM or bower?

### ISSUE THREAD

**Issue by girlssun** [Moerj/ngVerify#2]
How can I download this plugin via NPM or bower?

**Comment by girlssun** [comment]
I download by npm,it's error

**Comment by Moerj** [comment]
@girlssun 
this plugin can not download by NPM or bower.
you only need download two file.
[ **js/ngVerify.js**](https://github.com/Moerj/ngVerify/blob/master/js/ngVerify.js) and [**css/ngVerify.css**](https://github.com/Moerj/ngVerify/blob/master/css/ngVerify.css)


then you can install it like:
```html
<link rel="stylesheet" href="css/ngVerify.css">
<script src="js/ngVerify.js"></script>
```

or like webpack

```javascript
require('ngVerify.css');
require('ngVerify.js');
```
