### ISSUE TITLE
ngVerify.js:48 Uncaught TypeError: Cannot read property 'ngVerify' of undefined

### ISSUE THREAD

**Issue by girlssun** [Moerj/ngVerify#3]
When i use ngVerify.check('formName'),it's show that '
    ngVerify.js:48  Uncaught TypeError: Cannot read property 'ngVerify' of undefined
    at http://localhost:3000/public/plugins/verify/js/ngVerify.js:48:44';

**Comment by girlssun** [comment]
当使用ngVerify.check('formName')的时候会报错，报错信息如下：
ngVerify.js:48 Uncaught TypeError: Cannot read property 'ngVerify' of undefined
at http://localhost:3000/public/plugins/verify/js/ngVerify.js:48:44';
我看了一下ngVerify.js的48的代码为var els = scope.ngVerify.elems；
我尝试设置延长setTimeout的时间，也没用。

**Comment by Moerj** [comment]
在使用Verify的api前，需要在控制器上依赖注入。
 app.controller('yourCtrl',function(ngVerify){ ... })


<form name="formname" verify-scope >
</form>
你还要确保check的form是绑定了verify-scope 指令的，并有一个name值，然后再使用ngVerify.check('formName')

更详细的文档及用法请参考
https://segmentfault.com/a/1190000006612247
API ngVerify.check



发自我的 iPhone

**Comment by girlssun** [comment]
@Moerj 
我的html写法为  
```
<form class="" verify-scope="tipStyle: 2" name="fabricFactory" novalidate>
</form>
```
js页面使用ngVerify.check('fabricFactory');
还是存在我说的报错信息。

**Comment by Moerj** [comment]
@girlssun
请下载整个项目并运行，参考项目中的index.js  其中调用ngVerify.check的代码
