### ISSUE TITLE
ngVerify.checkElement()

### ISSUE THREAD

**Issue by girlssun** [Moerj/ngVerify#4]
当这样使用时：
       angular.element(document).find("input").each(function() {
                              if(!ngVerify.checkElement(this)){
                                ngVerify.checkElement(this,true);
                              }
                        })
会有报错信息，全部表单验证都显示错误（正确的也现实错误）；
当这样使用时：
  angular.element(document).find("input").each(function() {
                               console.log(ngVerify.checkElement(this));
                              if(!ngVerify.checkElement(this)){
                                ngVerify.checkElement(this,true);
                              }
                        })
会有报错信息，但是表单验证正确（只多了个console）；

**Comment by Moerj** [comment]
不能这样使用，checkElement 传入参数要求是id，name，或者是原生dom，并且是有ng-verify 指令的元素，例如：
<input id="One" ng-verify>

如果没有传入的id或name或原生dom不正确，dom上没有ng-verify，都会报错


你直接传入doucment下循环的input，这种用法不行。因为找到的input都不知道隶属于哪个form范围。

发自我的 iPhone

**Comment by girlssun** [comment]
angular.element(document).find("input").each(function() {
                          if($(this).attr("type") != "file"){
                            ngVerify.checkElement($(this).attr("name"));
                          }
});
根据你提供的解决方法，代码修改为这样。没有报错信息，但是验证失败。全部验证错误
@Moerj

**Comment by Moerj** [comment]
@girlssun

全部验证错误，说明插件已经工作了。
验证通过与否与你给的验证规则有关，你在每个input上定好验证规则了吗？默认无规则时，value不能为空!

**Comment by girlssun** [comment]
因为简单的测试，基本设置的是required：true。修改操作，都有值，但是验证错误。
