### ISSUE TITLE
校验规则能否动态传参

### ISSUE THREAD

**Issue by webthen** [Moerj/ngVerify#5]

**Comment by Moerj** [comment]
可以。但稍微麻烦一些。

![image](https://user-images.githubusercontent.com/13795438/57191830-5b3e6180-6f5c-11e9-96f1-40b46cb61ed0.png)

首先你需要定义一个变量test来改变参数，然后在定义一个布尔变量render来对对应的校验部位进行重绘刷新。

![image](https://user-images.githubusercontent.com/13795438/57191855-a6587480-6f5c-11e9-89a3-60f6614055b5.png)

当改变test时，用$timeout配置render重绘对应dom即可

**Comment by webthen** [comment]
3q




------------------ 原始邮件 ------------------
发件人: "萌耳君"<notifications@github.com>; 
发送时间: 2019年5月5日(星期天) 下午5:39
收件人: "Moerj/ngVerify"<ngVerify@noreply.github.com>; 
抄送: "kevin"<2749692744@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Moerj/ngVerify] 校验规则能否动态传参 (#5)




可以。但稍微麻烦一些。
 

 
首先你需要定义一个变量test来改变参数，然后在定义一个布尔变量render来对对应的校验部位进行重绘刷新。
 

 
当改变test时，用$timeout配置render重绘对应dom即可
